Update to whois to be a single Verifiable Presentation
trustoverip/tswg-did-method-webs-specification pull request #69
Opened 2023-10-13 19:29 UTC by swcurran

At IIW I was told that a Verifiable Presentation can contain an array of Verifiable Credentials, and as such it makes MUCH more sense for the `whois` to be a single Verifiable Presentation, with whatever Verifiable Credentials the DID Controller wants to publish.  I've reworded the PR accordingly.

I'd like to add to this if and how the publication of the Verifiable Presentation is accounted for in the keri.cesr file. Is there an operation that would be used for that?

2023-10-14 15:33 UTC, 2byrds commented
Looking forward to discussing this one @swcurran ! I'll prep a bit with the KERI community like @m00sey  who has engaged with VCDM significantly over the last year.

2023-10-18 16:55 UTC, 2byrds commented
@swcurran in order to address this I went back to the did core spec and did:web spec, for guidance. Neither of them include verifiable credentials/presentations as a part of their spec. The Did core spec mentions verifiable credentials as a down-stream use case for DIDs. The did:web spec doesn't mention VCs (that i saw).
So, I'm fairly certain this feature needs to be supported in a different spec.
But, to prep for our conversation about this, can you link me to the versions of the specs that you are seeking to support? You mention VCDM JSON-LD and JWT but as best as I can tell there are multiple versions that support those 1.0, 1.1, 2.0 and I'm not sure how that effects the associated presentations.
I look forward to learning more about your vision, but these kind of questions make it difficult to imagine including this kind of complexity in the did:webs spec.

2023-10-18 17:17 UTC, swcurran commented
The motivation is the same as the `whois` that is already in the draft spec, so that has not changed.  The same discussion we had when we merged that PR still applies with this one.  Its got nothing to do with DID Core (although it could benefit from this), just a did:webs feature that because of the nature of Web-based DIDs makes this feature incredibly useful feature extremely simple to implement.

What I’m proposing in this PR is to change the mechanism, so instead of the more complex process of doing a GET of folder of VCs/VPs, one only does a GET of “whois” and is rewarded with either a 404 (none) or a Verifiable Presentation that has one or more Verifiable Credentials.  It just makes the process easier.

I’ll review and revise before Friday, notably around the VCDM format.  Since 1.0 is obsolete, and 2.0 doesn’t yet exist, 1.1 is the target for now.  But that would be inherent in the published and retrieved VP so its not particularly relevant.

2023-10-24 10:25 UTC, dhh1128 commented
I agree with Lance's sentiment that this is not strictly a DID feature. However, I also understand why Stephen wants to mention it here. I think as long as we mention it in a way that makes it clear that it's an optional value-add (which I think Stephen's text does), it's fine to put it in this spec, so I would vote to merge. An alternative would be to say, in this spec, "This DID method enables a particularly convenient use of verifiable credentials that's documented in another spec, located [[here]]." I would also support that approach.

2023-10-24 10:26 UTC, dhh1128 approved these changes

2023-10-24 23:52 UTC, peacekeeper commented
>  So, I'm fairly certain this feature needs to be supported in a different spec.

There's a proposal for a work item now in the DIF ID WG to specify a way of discovering VPs associated with DIDs: https://hackmd.io/49Mp8tTTTRKmUGjjkWVoTw

It's not very concrete yet, but one approach is to define a service endpoint which links to VPs. This would work equally with any DID method, so it it's different from the approach here which uses "whois" DID URLs.

Anyway, I agree we can merge this here, and potentially attempt alignment with the DIF work item later once it matures a bit more.

2023-10-24 23:52 UTC, peacekeeper approved these changes

2023-10-27 16:24 UTC, 2byrds commented
From our meeting today:
There is desire for a separate spec, related to the DIF work here [Proposal for a DIF WG ID Work Item: Linked Verifiable Presentations](https://hackmd.io/49Mp8tTTTRKmUGjjkWVoTw)
For now @swcurran will expand the PR wording to mention ACDC presentations as part of the mime type detection. And we'll merge this and see how the efforts converge

2023-10-27 17:13 UTC, swcurran commented
Update the PR to reflect that the verifiable presentation might be an ACDC. 

I think this is now ready to merge, and has collected 2 approvals.  It is much better than what is in the spec today, so merging this sooner than later would be useful.

2023-10-27 17:20 UTC, 2byrds requested changes
I updated the link to the ACDC spec (ToIP).

2023-10-27 17:20 UTC, 2byrds commented on spec/whois.md
> +[An ACDC Verifiable Presentation]: https://www.ietf.org/archive/id/draft-ssmith-acdc-02.html
```suggestion
[An ACDC Verifiable Presentation]: https://trustoverip.github.io/tswg-acdc-specification/draft-ssmith-acdc.html
```

2023-10-27 17:41 UTC, swcurran commented on spec/whois.md
> +[An ACDC Verifiable Presentation]: https://www.ietf.org/archive/id/draft-ssmith-acdc-02.html
Thanks — updated and pushed.

2023-10-27 18:10 UTC, 2byrds approved these changes

2023-10-27 18:10 UTC, merged