Security considerations amended
trustoverip/tswg-did-method-webs-specification pull request #71
Opened 2023-10-16 19:15 UTC by henkvancann

I added a reason to the list (compatibility with did:web), but not sure if that's valid.

Furthermore, I've suggested a few why's and how's of the list that you should maybe want to take a close look at.

2023-10-16 19:21 UTC, henkvancann commented
1. it safeguards privacy (this is implicitly offered by the https protocol)
2. discourages denial of service attacks (HOW?), 
3. accords with a defense-in-depth mindset (WHY?), 
4. aids regulatory compliance (because we'd comply with common technologic practise),
5. establishes backwards compatibility with `did-web` (for we would use exactly the same form),
6. and makes it easier to troubleshoot (HOW/WHY?).

2023-10-17 13:07 UTC, 2byrds requested changes
Privacy/https fix is the biggest change needed.

2023-10-17 13:15 UTC, henkvancann commented on spec/security_considerations.md
> +1. it safeguards privacy (this is implicitly offered by the https protocol)
I just regrouped formatted it in a list, did not introduce the word 'privacy'
but I do agree we need to reconsider the wording
Maybe we discuss this briefly next meeting?

2023-10-17 23:07 UTC, henkvancann commented
> Privacy/https fix is the biggest change needed.

done

2023-10-19 14:06 UTC, closed without merging