Typos, definitions, and KERI Fundamentals section
trustoverip/tswg-did-method-webs-specification pull request #85
Opened 2023-11-26 07:13 UTC by nkongsuwan

This PR makes the following changes:
- In `whois.md`, remove inconsistent capitalization for “Verifiable Credentials” and “Verifiable Presentations”, now all lowercase.
- In `security_characteristics.md`, change “KEL-backed” to “KEL backed” to improve insistency.
- In `diddocuments.md`, remove an identical code block in one of example DID docs.
- In `diddocuments.md`, correct a threshold from 6 to 12.
- In `terminology.md`, add minor changes and improve format consistency.
- In `keri.md`, remove `[[def: ...]]` and add references to the terminology. I also make the writing sound more formal and add references to other sections.

All occurrences of `[[def: ...]]` are now located in the terminology.

2023-11-26 23:12 UTC, 2byrds requested changes
@nkongsuwan this is great work! In the KERI section it feels like we are defining terms but referencing the terminology section. I started commenting on each section but it applies across all the definitions in the keri.md. I'm open to discussing the strategy but I feel like we should talk about what did:webs is getting from that aspect of KERI (without defining it) and allow terminology to give a highlight definition and allow KERI docs to provide the details. What do you think?

2023-11-26 23:12 UTC, 2byrds commented on spec/keri.md
> +An [[ref: autonomic identifier (AID)]] is a globally-unique persistent self-certifying identifier that serves as the primary root-of-trust of the KERI protocol. An AID is cryptographically bound to a
It seems to me if we are going to define AID in terminology then we shouldn't define it here. We should instead only explain the significance of the AID to the DID. So then first two sentences should be handled by the def, and then the following sentences belong here. Thoughts?

2023-11-26 23:12 UTC, 2byrds commented on spec/keri.md
> +The binding between an [[ref: AID]] and its cryptographic keys is proved by a data structure called a [[ref: key event log (KEL)]] that allows the [[ref: key states]] of the AID to evolve. For a `did
Same comment about the definition being in terminology (see above) so this section shouldn't have the first sentence.

2023-11-26 23:12 UTC, 2byrds commented on spec/keri.md
> +A KEL is a hash-chain append-only log and can be considered a variant of blockchain. However, a KEL differs from the traditional blockchain technology in at least two important ways:
move to terminology.

2023-11-26 23:12 UTC, 2byrds commented on spec/keri.md
> +2.  It is fully [[ref: self-certifying]], meaning its correctness can be proved by direct inspection, without a distributed consensus algorithm or assumptions about trust in an external data source o
Move to terminology or allow KERI terminology to cover this.

2023-11-26 23:12 UTC, 2byrds commented on spec/keri.md
> +The value of an [[ref: AID]] is derived from the first [[ref: key event]], called the [[ref: inception event]], of a [[ref: KEL]]. The inception event includes inital public key(s), called the _curre
Move to terminology or let KERI wiki provide this info.

2023-11-26 23:12 UTC, 2byrds commented on spec/keri.md
> +### Pre-rotation
Move to terminology or let KERI wiki provide this info.

2023-11-26 23:12 UTC, 2byrds commented on spec/keri.md
> +The [[ref: KERI]] protocol supports weighted multi-signature scheme that allows for [conditional proof](#thresholds) in the [Verification Methods](#verification-methods). A multisig [[ref: AID]] dist
Move to terminology or let KERI wiki provide this info.

2023-11-30 13:23 UTC, 2byrds approved these changes
Lets push the conversation about merging the keri.md and the terminology.md into a future issue/PR

2023-11-30 13:24 UTC, 2byrds commented on spec/keri.md
> +The value of an [[ref: AID]] is derived from the first [[ref: key event]], called the [[ref: inception event]], of a [[ref: KEL]]. The inception event includes inital public key(s), called the _curre
Pushing to a future convo/issue/PR

2023-11-30 13:24 UTC, 2byrds commented on spec/keri.md
> +The [[ref: KERI]] protocol supports weighted multi-signature scheme that allows for [conditional proof](#thresholds) in the [Verification Methods](#verification-methods). A multisig [[ref: AID]] dist
Pushing to a future convo/issue/PR

2023-11-30 13:24 UTC, 2byrds commented on spec/keri.md
> +2.  It is fully [[ref: self-certifying]], meaning its correctness can be proved by direct inspection, without a distributed consensus algorithm or assumptions about trust in an external data source o
Pushing to a future convo/issue/PR

2023-11-30 13:24 UTC, 2byrds commented on spec/keri.md
> +A KEL is a hash-chain append-only log and can be considered a variant of blockchain. However, a KEL differs from the traditional blockchain technology in at least two important ways:
Pushing to a future convo/issue/PR

2023-11-30 13:24 UTC, 2byrds commented on spec/keri.md
> +The binding between an [[ref: AID]] and its cryptographic keys is proved by a data structure called a [[ref: key event log (KEL)]] that allows the [[ref: key states]] of the AID to evolve. For a `did
Pushing to a future convo/issue/PR

2023-11-30 13:25 UTC, merged

2023-12-01 03:17 UTC, nkongsuwan commented
@2byrds In my opinion, the terminology section should be brief, allowing for mouseover texts. The KERI Fundamentals section should contain concise definitions of important KERI concepts such as AID and KEL so that the `did:webs` specification is reasonably self-contained. However, I struggled to find the delicate balance between giving too much and too little details. So I decided to go with putting too much details and then leave the decision to trim things down to you and the other editors.